name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  MSSQL_PASSWORD: My_1Strong_password
  SECRET_KEY: 50w3xPXb3LUYbDaKJarItPcNk3EIF1gz

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: "Y"
          MSSQL_SA_PASSWORD: "$MSSQL_PASSWORD"
        ports:
          - 1433:1433
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build server
        run: ./gradlew :server:build -x test
      - name: Build client
        run: ./gradlew :client:build -x test
      - name: Test server
        env:
          DEV_DATASOURCE_URL: "jdbc:sqlserver://localhost:1433;trustServerCertificate=true"
          DEV_DATASOURCE_USERNAME: "sa"
          DEV_DATASOURCE_PASSWORD: "$MSSQL_PASSWORD"
          SECRET_KEY: "$SECRET_KEY"
        run: ./gradlew :server:test